### ISSUE TITLE
laden startet sofort

### ISSUE THREAD

**Issue by merlinfive** [thps1990/TeslaChargejs#1]
Hi ,

bin erst seit 2 Tagen iobroker Nutzer , habe iobroker am laufen , Tesla eingebunden , sma-em (homemanager 2.0 )eingebunden und javascript angelegt. 
Es wurden auch die Objekte angelegt und ich sehe auch Werte . Sobald ich aber den Tesla anstecke beginnt auch das laden , auch ohne "Sonne".

Ich vermute mein Problem hier , muß da was von sma-em rein ?

//IOBroker Objekt ID der Einspeiseleistung PV 
const ID_EINSPEISE_LEISTUNG         = "OBJEKT.PV.EINSPEISUNG_LEISTUNG"; //Watt  

 //IObroker Objekt ID der Netzbezugsleistung PV
const ID_NETZBEZUG_LEISTUNG         = "OBJEKT.PV.NETZBEZUG_LEISTUNG" ; //Watt

Danke und Gruß

**Comment by merlinfive** [comment]
ok , habe jetzt die richtigen Parameter für Einspeisung und Netzbezug eingetragen , er startet das laden wenn genügend PV vorhanden ist aber nicht mit der Stromstärke im Script sondern mit der im Auto mal gesetzten , Tesla Model S .
In der Folge geht die Ladeleistung auf 22KW hoch , Meldung zu wenig PV und beendet das laden .
charge_amps gibt es bei mir nicht , werde mal current versuchen
![Chargejs1](https://user-images.githubusercontent.com/101570702/159001088-a69ba1f7-6bfa-422e-8d51-bfecd12cf867.PNG)
![Chargejs2](https://user-images.githubusercontent.com/101570702/159001245-21286bfb-5c88-4e7f-90f7-d2160c7f20cc.PNG)

**Comment by thps1990** [comment]
Das Auto wird immer sofort das laden beginnen und das immer mit der Stromstärke, die im Auto eingestellt ist. Das macht der Tesla von sich aus. Der Tesla Adapter ist auch nicht schnell genug um das zu erkennen und abzufangen. 

Was  allerdings passieren müsste ist, dass das Skript die Amperezahl immer weiter reduziert, bis es schlussendlich die Ladung stoppt, je nachdem wieviel Sonne vorhanden ist. Wenn die PV-Anlage wieder genug Strom liefert, sollte die Ladung dann mit den Start-Ampere starten. 

Ich selbst habe leider nur ein Model 3 und bin über den Input dankbar.

**Comment by merlinfive** [comment]
Hi gefunden , es lag an meiner alten Firmware im Auto , seit WE haben auch unsere "Oldies" die V11 mit der Einstellmöglichkeit über die App und somit auch über die API , funktioniert top .
Hätte einen Feature request :-) , könnte man das Script so anpassen das es quasi nur von Sonnenaufgang bis Sonnenuntergang aktiv ist (z.B. 6:00-22:00) und in der übrigen Zeit das laden bei zu wenig PV nicht unterbricht ?

**Comment by JulianLoeffler** [comment]
@merlinfive die Zeit kannst du selbst einstellen, falls du Javascript in IoBroker nutzt. Da gibt es einen Timer.

**Comment by morpeuse** [comment]
> @merlinfive die Zeit kannst du selbst einstellen, falls du Javascript in IoBroker nutzt. Da gibt es einen Timer.

Ich habe keinen Timer gefunden. Wo finde ich den im Skript. Kannst du mir diesen zeigen?

**Comment by thps1990** [comment]
> 

Da gibts es auch noch keinen Timer der das unterstützt. Ich kann aber gerne mit einbauen, dass das Skript nur zwischen Sonnenauf- und Sonnenuntergang regelt...

**Comment by thps1990** [comment]
> > @merlinfive die Zeit kannst du selbst einstellen, falls du Javascript in IoBroker nutzt. Da gibt es einen Timer.
> 
> Ich habe keinen Timer gefunden. Wo finde ich den im Skript. Kannst du mir diesen zeigen?

Ich habs in Version 1.9 mit eingebaut
