### ISSUE TITLE
Mindest Stromstärke nicht konfigurierbar

### ISSUE THREAD

**Issue by MeisterQ** [thps1990/TeslaChargejs#10]
Ich habe gesehen, dass der Startstrom bei 5A liegt, und das Skript nur bis 5A runter regelt.

Der Tesla kann aber mit der API bis auf 0A geregelt werden (Auch wenn mindestens immer 2A fließen wenn man 0A vorgibt)

Wäre das noch zu ändern? So kann man noch feiner Regeln, gerade wenn es abend wird und die PV Leistung Abfällt.

**Comment by Hal-us2010** [comment]
Bei mir regelt das Script bis auf 700 Watt Ladeleistung herunter. Das ist weniger als 1A bei drei Phasen.
Allerdings wid dann der Wirkungsgrad grottig, da der Tesla schon ohne Ladung ca. 300W benötigt

**Comment by thps1990** [comment]
Du kannst als Start Stromstärke eintragen was du willst. Damm geht das Skript auch bis auf 1 oder 2 A runter. Am 04.05.2023 19:29 schrieb Andreas ***@***.***>:
Ich habe gesehen, dass der Startstrom bei 5A liegt, und das Skript nur bis 5A runter regelt.
Der Tesla kann aber mit der API bis auf 0A geregelt werden (Auch wenn mindestens immer 2A fließen wenn man 0A vorgibt)
Wäre das noch zu ändern? So kann man noch feiner Regeln, gerade wenn es abend wird und die PV Leistung Abfällt.

**Comment by MeisterQ** [comment]
> Du kannst als Start Stromstärke eintragen was du willst. Damm geht das Skript auch bis auf 1 oder 2 A runter. Am 04.05.2023 19:29 schrieb Andreas ***@***.***>: Ich habe gesehen, dass der Startstrom bei 5A liegt, und das Skript nur bis 5A runter regelt. Der Tesla kann aber mit der API bis auf 0A geregelt werden (Auch wenn mindestens immer 2A fließen wenn man 0A vorgibt) Wäre das noch zu ändern? So kann man noch feiner Regeln, gerade wenn es abend wird und die PV Leistung Abfällt. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Was hat es hiermit aufsich?

`                    if(Netzbezug > MAXIMAL_NETZBEZUG)
                    { // Zu VielNetzbezug --> Laden abbrechen
                        timeout_running = true;
                        setTimeout(function(){
                            timeout_running = false;
                            refresh_data();
                            if(Netzbezug > MAXIMAL_NETZBEZUG && getState(ID_TSL_GET_AMPS).val < 6)
                            {// Laden Stoppen 
                                setState(ID_TSL_CMD_CHARGE_STOP,true);
                                log("Laden gestoppt, zu wenig PV-Leistung vorhanden",false,true);
                            }
                        },ENTPRELL_ZEIT * 60000);
                    }`
                    
Da sind ja <6 A fest einprogrammiert. Da könnte man ja auf die Startstromstärke nutzen, damit er da noch weiter runter geht, oder den Wert <= 2 setzen weil das Auto nur bis 2A runter regelt. (Zumindest mein M3 BJ22).

Weil sonst würde ja bei zu viel Netzbezug unter 6A das Laden Abgebrochen werden, selbst wenn man da noch 3A runter regeln kann

**Comment by thps1990** [comment]
Da hast du recht, da stehen die 6 A noch hart verdrahtet drin. 
Das ist gefixt in https://github.com/thps1990/TeslaChargejs/releases/tag/V1.9.3

**Comment by MeisterQ** [comment]
Danke
