### ISSUE TITLE
feinere Amper abstimmung

### ISSUE THREAD

**Issue by Schimi1983** [thps1990/TeslaChargejs#15]
HI,

zur Zeit wird ja die Stromsätke in "vollen" Ampere geregelt....

Könnte man das auch auf 0.5 Sprünge ändern? Oder ist es eine API limitierung (in der App geht ja uch nur ganze Amp)

**Comment by thps1990** [comment]
Hi, Das ist leider nicht möglich. Am 06.05.2023 09:54 schrieb Schimi ***@***.***>:
HI,
zur Zeit wird ja die Stromsätke in "vollen" Ampere geregelt....
Könnte man das auch auf 0.5 Sprünge ändern? Oder ist es eine API limitierung (in der App geht ja uch nur ganze Amp)
