### ISSUE TITLE
Überschussladen stoppt nicht

### ISSUE THREAD

**Issue by janhp** [thps1990/TeslaChargejs#16]
Lieber DEV, 

Ein klasse Projekt und bisher funktioniert das Skript auch wunderbar. Allerdings gibt es noch einen Bug: Und zwar wird bei aktivierten Überschussladen und zu wenig PV (ohne PV Battery) zwar die Amps auf 5amp runtergeregelt, jedoch wird der Ladevorgang nicht gestoppt (sonder lädt mit 5amp weiter - obwohl ich die Variable const MAXIMAL_NETZBEZUG auf 100watt gestellt habe.

Wäre klasse, wenn du das fixen könntest :) Danke!

**Comment by ralflr** [comment]
da die Startstromstärke,  auch die  min Stromstärke ist, wird der Ladestrom bis zur Startstromstärke reduziert. 
in Zeile 281 ein = ergänzen, hat bei mir geholfen


`281c281`
`<                                 if(Netzbezug > MAXIMAL_NETZBEZUG && getState(ID_TSL_GET_AMPS).val <= START_STROMSTAERKE)`
`---`
`>                                 if(Netzbezug > MAXIMAL_NETZBEZUG && getState(ID_TSL_GET_AMPS).val < START_STROMSTAERKE)`

**Comment by thps1990** [comment]
Hi, 

danke für die Info, das ist in V1.9.4 gefixt.

vg
