### ISSUE TITLE
Skript mit Teslamate statt iobroker.tesla-motors laufen lassen

### ISSUE THREAD

**Issue by jensb** [thps1990/TeslaChargejs#2]
Hallo, ich nutze iobroker und würde dieses Skript gerne nutzen, aber ich habe Teslamate zur Autoüberwachung aktiv (nutzt PostgreSQL + eine eigene Web-UI) und nicht den iobroker-Tesla Adapter.
Welche Eingangsdaten braucht der Tesla-Adapter vom Auto und wie wird das Laden gestartet / gestoppt? Vielleicht kann ich das Skript umbiegen, ein MQTT-Interface hat Teslamate auch und das habe ich auch in ioBroker eingebunden, aber natürlich heißen die states teilweise anders. Ich würde dein Skript dann forken, vielleicht könntest du mir ein wenig Starthilfe geben?
Danke!

**Comment by thps1990** [comment]
Hallo,

das sollte eigentlich kein Problem sein. Du musst nur alle Konstanten die mit "ID_TSL" beginnen mit deinen Objekten von Teslamate befüllen.
Das müsste eigentlich funktionieren.
Oder halt einfach zusätzlich den Tesla-Adapter installieren. Das tut ja eigentlich nicht weh.

VG

Torsten
________________________________
Von: jensb ***@***.***>
Gesendet: Sonntag, 11. September 2022 14:51
An: thps1990/TeslaChargejs ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [thps1990/TeslaChargejs] Skript mit Teslamate statt iobroker.tesla-motors laufen lassen (Issue #2)


Hallo, ich nutze iobroker und würde dieses Skript gerne nutzen, aber ich habe Teslamate zur Autoüberwachung aktiv (nutzt PostgreSQL + eine eigene Web-UI) und nicht den iobroker-Tesla Adapter.
Welche Eingangsdaten braucht der Tesla-Adapter vom Auto und wie wird das Laden gestartet / gestoppt? Vielleicht kann ich das Skript umbiegen, ein MQTT-Interface hat Teslamate auch und das habe ich auch in ioBroker eingebunden, aber natürlich heißen die states teilweise anders. Ich würde dein Skript dann forken, vielleicht könntest du mir ein wenig Starthilfe geben?
Danke!
