### ISSUE TITLE
Datenpunkt zum Aussetzen des Scriptes

### ISSUE THREAD

**Issue by severendis** [thps1990/TeslaChargejs#3]
Hallo an den Entwickler!

Wirklich eine sehr gute Arbeit!

Ich würde mir einen Datenpunkt "Script aktiv" wünschen, den ich beliebig zwischen true und false schalten kann.
Muss ich mein Auto laden, auch wenn keine Sonne da ist, dann könnte ich dafür das Script leicht über den Datenpunkt deaktivieren.
So muss ich ich das Script im WEBIF in JS anhalten und dafür immer an den PC.

Vielen Dank schon mal!

Uwe

**Comment by thps1990** [comment]
Hallo Uwe, 

diesen Datenpunkt gibt es bereits. Er wird automatisch mit angelegt beim ersten Ausführen des Skripts. Du findest ihn unter:
"0_userdata.0.TeslaChargejs.Ueberschussladung_aktiv"  --> TRUE = an, FALSE= aus. 

Viele Grüße

THPS
