### ISSUE TITLE
Netzbezug und Einspeisung über einen Zähler

### ISSUE THREAD

**Issue by Schimi1983** [thps1990/TeslaChargejs#5]
HI,

dein Skript ist sehr interessant...

Aber was muss ich eintragen wenn ich meinen Zähler über IR auslese und der bezug mit z.B: "625 Watt" und die Einspeisung mit z.B. "- 630 Watt" im gleichem Objekt ausgegeben wird....

Soll ich bei "ID_NETZBEZUG_LEISTUNG" und "ID_EINSPEISE_LEISTUNG" jeweils den gleichen Datenpunkt angeben?

**Comment by thps1990** [comment]
Hi, 
Man müsste die beiden Werte trennen. 
Ich kann das nächste Woche in das Skript mit einbauen. 
Alternativ kannst du ein zusätzliches  Skript oder Blockly schreiben, dass den Wert für Bezug und Einspeisung in jeweils andere Datenpunkte schreiben je nachdem ob der Wert gerade positiv oder negativ ist.

**Comment by thps1990** [comment]
Ich habe das in einem Beta-Release mal umgesetzt: https://github.com/thps1990/TeslaChargejs/releases/tag/V1.9.1-beta

Deinen Datenpunkt als "ID_EINSPEISE_LEISTUNG" eintragen und bei ID_NETZBEZUG_LEISTUNG "" (also leer) eintragen. 

Das Skript erzeugt sich dann automatisch 2 Datenpunkte und nimmt die Werte auseinander


Bitte ml testen

**Comment by Schimi1983** [comment]
Hi,

mist gerade erst gesehen... werde es ausprobieren... kann aber nen paar Tage dauern... habe nicht damit gerechnet das es so schnell geht (als Kompliment gemeint) und im Urlaub lade ich gerade "wo anders" ;-)

**Comment by thps1990** [comment]
Kein Problem, das war kein großes Ding. Ich brauche nur einen Tester, weil ich das Skript selbst nicht mehr einsetze und auch getrennte Objekte für Netzbezug und Einspeisung habe.

**Comment by Schimi1983** [comment]
HI,

es scheint zu funktionieren.... Bei der "Sonne" gerade kommt er zwar nicht über 4A... aber er scheint zu regeln....

**Comment by thps1990** [comment]
Sehr schön
