### ISSUE TITLE
Keine Anpassung der Ladestärke am Nachmittag bei nachlassender PV-Leistung

### ISSUE THREAD

**Issue by Sir-Lunch-a-Lot** [thps1990/TeslaChargejs#6]
Erst mal auch von meiner Seite ein grosses Lob an den Entwickler! Ich nutze auch die aktuelle Beta und bislang klappt es wunderbar. 

Was mir aufgefallen ist: Bei Überschuss passt das Script die Ladestärke vom Tesla nach oben an, bis die Netzeinspeisung minimal ist und das Maximum ins Auto pumpt. 
Am Nachmittag jedoch senkt er die Ladestärke vom Tesla nicht ab und saugt den Rest aus dem Hausakku, bis der MindestSOC erreicht (94%) ist. Dann bricht das Script das Überschussladen ab. Danach wird wieder neu gestartet, wenn der Hausakku den SOC von 100% und das Laden des Autos beginnt von vorne, bis wieder der MindestSOC vom Hausakku erreicht ist. 

Im Haus wäre eine Anlage von E3DC vorhanden und würde bei der Fortentwicklung zumindest als Tester beitragen wollen, wenn gewünscht ;-)

**Comment by thps1990** [comment]
Hi,
ich nutze das Skript selbst nicht mehr, kann es aber gerne noch anpassen. 
Was wäre denn das gewünschte Verhalten?

**Comment by Sir-Lunch-a-Lot** [comment]
Was hast denn als Alternative? Wär auch für anderes offen. 

M.M. nach wäre es ideal, wenn kein Netz-/Hausakkubezug gesetzt ist (wie bei Z. 27) und das Auto Strom aus dem Netz bzw. Hausakku ziehen würde, die Ladestärke des Autos soweit reduzieren würde, dass nur er Überschuss geladen wird. Wenn die Mindestladestärke unterschritten wird, dann sollte er abbrechen. 

Ich weiss nur nicht, ob beim bisherigen Script das berücksichtigt ist. Die Zeilen 79 und 82 hätt ich definiert. 

Gruss

**Comment by thps1990** [comment]
Wir haben noch ein 2. E-Auto bekommen. Das ist kein Tesla, also habe ich mir ein Skript geschrieben, das die Wallbox steuert.

Ich denke morgen mal drüber nach, wie man das Skript noch anpassen könnte.

**Comment by thps1990** [comment]
Mmh ich habs mir nochmal angeschaut und so richtig hab ich das Problem nicht verstanden. Es gibt einen Mindestakkustand, ab dem kann generell die Ladung gestartet werden, wenn genug Leistung zur Verfügung steht . Die Mindestleistung legst du mit MINDEST_EINSPEISE_LEISTUNG fest. 
Wenn du jetzt z.B. Einphasig lädst und als Mindesteinspeiseleistung 1400 Watt festlegst, wird er das laden nur starten wenn der Akku mindestes die X % hat und dennoch noch mehr eingespeist wird als 1400 Watt. Andersherum legst du mit dem MAXIMAL_NETZBEZUG fest, wieviel maximal aus dem Netz/Akku gezogen werden darf. Wenn du das nahe 0 setzt, wird er den Akku nicht wieder unter den Mindest SoC entladen

**Comment by Sir-Lunch-a-Lot** [comment]
Ok ich teste mal. Ich schliesse eine Fehlbedienung meinerseits nicht aus😉
