### ISSUE TITLE
Laden startet morgens automatisch für ca. 1h

### ISSUE THREAD

**Issue by morpeuse** [thps1990/TeslaChargejs#7]
Mir ist aufgefallen das heute morgen die Ladung kurz vor 6Uhr gestartet wurde und dann erst nach ca 1h beendet wird, da nicht ausreichend Überschuss vorhanden ist. 

1. Warum wird das Laden automatisch gestartet obwohl kein Überschuss vorhanden ist
2. Was bedeutet die Nachricht restarting und  started!
3. Warum wird erst nach ca. 1h das laden unterbrochen? - meine Erklärung wäre das die Sonne 6:50 aufgeht und auch erst dann das Skript runter regelt bis es gestoppt wird

Ich habe die Version 1.9 bei mir am laufen. 
Was sonst super funktioniert. 
Danke für das coole Skript 

kann mir wer das Verhalten erklären. 

![IMG_9316](https://user-images.githubusercontent.com/41719610/229114880-ffaf692a-7563-4eee-9fc1-cbf7c952e8d7.jpeg)
![IMG_9315](https://user-images.githubusercontent.com/41719610/229114890-fe6342e5-00c5-43f1-b884-714dbbccbc47.jpeg)

**Comment by thps1990** [comment]
Hi, also 

zu 1.: Zu dieser Uhrzeit reagiert das Skript noch gar nicht. Das prüft auf Sonnenauf- und Untergang. Sprich vor ca. 7 Uhr macht das Skript gar nichts.

zu 2.:  Die Nachricht kommt nicht von dem Skript. Das könnte vom Telegram Adapter kommen

zu 3.: Das Skript stoppt die Ladung erst nach 1h, weil es erst ab Sonnenaufgang überhaupt agiert. Vorher ignoriert es alles. 


Hast du zufällig noch ein anderes Tool laufen, was deine Tesla Zugangsdaten hat? (Jedlix, Teslafi,....) Oder hast du einen Ladetimer im Tesla aktiv? 

VG

THPS

**Comment by morpeuse** [comment]
Danke für die Erklärung.

zu1.: ich habe hier folgendes herrausgefunden
[Tesla Model Y startet Ladevorgang selbständig](https://tff-forum.de/t/tesla-model-y-startet-ladevorgang-selbstaendig/261839)

zu 2.: konnte ich hiermit lösen. 😀 einfach die beiden Zeilen löschen.
![Bildschirmfoto 2023-03-31 um 14 38 00](https://user-images.githubusercontent.com/41719610/229122259-21a4fa41-e1c0-45c3-be04-3aa67858bbe9.png)

zu 3.: Gibt es eine Möglichkeit AstroDay zu deaktivieren. Das sofort wieder untergeregelt wird wenn das laden selbständig startet und PV-Überschuss aktiv ist.

Ich habe Tronity am laufen sonst kein weiteres Tool der Ladetimer ist deaktiviert.

**Comment by thps1990** [comment]
ok, ich könnte einbauen, dass die Ladung generell gestoppt wird, wenn die Überschussladung aktiv ist und gerade kein Tag ist. Das wäre relativ einfach möglich. Dann würde er relativ schnell die Ladung wieder stoppen falls das vorkommt.

**Comment by morpeuse** [comment]
Mega das wäre super.

Am Wochenende stecke ich, wenn ich Freitag abends nach Hause komme das Kabel rein und PV-Überschussladen ist aktiviert. Damit am nächsten morgen, sobald Überschuss da ist das Auto anfängt mit laden. 

Vielen dank für deine Bemühungen. 😀

Welche Wallbox nutzt du jetzt nachdem du ein zweites eAuto gekauft hast?

**Comment by thps1990** [comment]
Ich hab das mal in ein neues Beta Release gegossen: https://github.com/thps1990/TeslaChargejs/releases/tag/V1.9.2-beta
Bitte testen :)

Ich nutze seit 2020 einen Go-E Charger

**Comment by morpeuse** [comment]
Hey, 
hab es jetzt testen können. Laden wird nach ca. 5-10 sek gestoppt.
![Bildschirmfoto 2023-04-03 um 20 38 21](https://user-images.githubusercontent.com/41719610/229597947-e3339dae-fbcc-4fdc-aa72-412eb2e8211b.png)

Gibt es auch die Möglichkeit bei Deaktivierung von PV-Überschussladen das der Wert nicht auf 16A im Fahrzeug gestellt wird. Sondern nur auf 5A oder vielleicht auf den Wert der vorher im Fahrzeug eingestellt war.

Vielen Dank für dein cooles Skript und deinen Einsatz.

**Comment by thps1990** [comment]
Also der vorher eingestellte Wert ist eher nicht möglich. Ich könnte einen festen Parameter hinzufügen, mit dem du einen festen Wert festlegen kannst.

**Comment by morpeuse** [comment]
Hey, sorry für die Späte Rückmeldung. Das wäre super wenn man hier einen festen Wert definieren könnte mit dem das Skrip startet wen PV-Überschussladen deaktiviert wird. Danke für dein Unterstützung und Zeit.
