### ISSUE TITLE
Fehler bei Stoppen des Skriptes

### ISSUE THREAD

**Issue by jensb** [thps1990/TeslaChargejs#8]
Hallo,
erst einmal großes Lob an den Entwickler - das Skript funktionierte (fast) auf Anhieb und es passt die Ladestärke automatisch nach oben an. (Noch nicht ganz so wie ich mir wünsche, aber ich schaue noch...)

Aber ein kleines Problem (ist es eins?) habe ich gefunden: Ich bekomme immer, wenn ich das Skript stoppe (manchmal müssen wir auch einfach mit 16A vollladen, egal wie das Wetter gerade ist) diese Meldungen im Log:

javascript.0 | 2023-04-15 14:48:26.273 | error | (COMPACT) Error by canceling scheduled job "<Anonymous Job 31 2023-04-15T12:32:42.215Z>"
javascript.0 | 2023-04-15 14:48:26.273 | error | (COMPACT) Error by canceling scheduled job "<Anonymous Job 30 2023-04-15T12:32:42.209Z>"
javascript.0 | 2023-04-15 14:48:26.273 | error | (COMPACT) Error by canceling scheduled job "<Anonymous Job 29 2023-04-15T12:32:42.204Z>"

Ist das ein Problem? Wenn ja, wie bekomme ich es weg?

Danke!

**Comment by thps1990** [comment]
Hi, 

das ist eigentlich kein Problem. Aber eigentlich musst du das Skript gar nicht stoppen. Das Skript erzeugt ein Objekt "0_userdata.0.TeslaChargejs.Ueberschussladung_aktiv" . Wenn du das auf "false" setzt, dann lädt dein Auto unabhängig von der PV-Anlage wieder mit maximaler Ladeleistung.
